### ISSUE TITLE
Scenario handling and indexing

### ISSUE THREAD

**Issue by brookscl** [pacman-ghost/asl-articles#1]
I figured this was as good a place as any to ask a question / make a suggestion. First want to say that I started using this today after exploring your VASL Template app. I wasn't sure of the value of asl-articles but decided to get it running and check it out. The app is simple and effective -- thank you for making it.

Do you have plans to continue working on this, and are you open to PRs? I'm working on indexing my recently purchased bundles of the ASL Annual and ASL Journal, and given the rich scenario content there I thought it might be nice to add scenario indexing as a first class feature.

**Comment by pacman-ghost** [comment]
> The app is simple and effective -- thank you for making it. 

Thanks :-)

> Do you have plans to continue working on this

I've actually done quite a bit of work on this since the last push, and have been dog-fooding it. I'll prepare a new release shortly. I think you'll be pleasantly surprised :-)

However, I would suggest you hold off loading up your database for now, since the schema's changed and while I *think* it will be backwards-compatiblie, it's been a while... :-)

> are you open to PRs? I'm working on indexing my recently purchased bundles of the ASL Annual and ASL Journal, and given the rich scenario content there I thought it might be nice to add scenario indexing as a first class feature. 

Possibly, but how would you see such a feature working? I specifically didn't add something like this because (1) there are already places that do this e.g. the ASL Scenario Archive and ROAR, and (2) how would it integrate with ASL Articles? 

I don't have a beard, but if I did, it would be grey, and I'm a big believer in applications doing one thing, and doing it well. For asl-articles, the only thing I care about when it comes to scenarios is finding articles it has been referenced in (e.g. because I'm about to play a scenario, and I want to find some hints about how to play it), and a simple full-text search on the scenario ID and name lets me do that. There doesn't seem to be a strong case for making this program asl-articles-and-scenarios :-)

I thought about making the scenarios link to ROAR or the ASL Scenario Archive, but it would be very messy (due to data quality issues), and far more work than it would be worth.

**Comment by brookscl** [comment]
First things first: I think I can achieve what I want without modification to the app. But let me explain the use case a bit more and maybe you'll get where I'm coming from.

I have a wide assortment of PDF-ized scenarios and they are roughly organized in folders. Some are official PDF sets I've purchased online (e.g., through the ASL Scenario Archive store), so are scans I've made of my own set, some are in magazines.

The niche I see your tool filling here is a way to tag and index these in a way that doesn't force me to break these individual PDF pages out of sets or magazines. I'm certainly not trying to replace what ROAR or the archive do (though linkage to the archive wouldn't be bad!). 

Example:

1. I search on ASL Scenario Archive for candidate scenarios to play (I've run some tournaments as well, so sometimes I'm looking for something that fits a theme or similar constraint).
2. I pull up this tool to see if I have it in my collection.

All that said, with tagging I can achieve the same end by just treating each of the scenarios as an article.

**Comment by brookscl** [comment]
Side note: I was able to pull the latest commits, run the alembic upgrade, and everything works fine with my in-place database.

**Comment by pacman-ghost** [comment]
> The niche I see your tool filling here is a way to tag and index these in a way that doesn't force me to break these individual PDF pages out of sets or magazines. 

OK, I get it and yes, the way to do this would be to treat each scenario as an "article." You could even include additional metadata as the article snippet, which would then be searchable :-)

>  was able to pull the latest commits, run the alembic upgrade, and everything works fine with my in-place database.

I did a diff on models.py, and it turned out there weren't that many changes in the end, and the code should be able to handle the new fields correctly.
